// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/library.dart';
import 'api/song.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiLibraryInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2087443467;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_songbook',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSongSimpleSongAsText({required SimpleSong that});

  void crateApiSongSimpleSongChangeFromEdited({
    required SimpleSong that,
    required String s,
  });

  void crateApiSongSimpleSongDetectKey({required SimpleSong that});

  SimpleSong crateApiSongSimpleSongFromChordpro({required String pathStr});

  List<SimpleSong> crateApiSongSimpleSongFromSongbookpro({
    required String pathStr,
  });

  String crateApiSongSimpleSongGetArtist({required SimpleSong that});

  BigInt? crateApiSongSimpleSongGetAutoscrollSpeed({required SimpleSong that});

  List<SimpleBlock> crateApiSongSimpleSongGetBlocks({required SimpleSong that});

  int? crateApiSongSimpleSongGetCapo({required SimpleSong that});

  Map<String, String>? crateApiSongSimpleSongGetFingerings({
    required SimpleSong that,
  });

  String crateApiSongSimpleSongGetForEditing({required SimpleSong that});

  String? crateApiSongSimpleSongGetKey({required SimpleSong that});

  Future<void> crateApiSongSimpleSongGetMutSong({required SimpleSong that});

  String? crateApiSongSimpleSongGetNotes({required SimpleSong that});

  String? crateApiSongSimpleSongGetPath({required SimpleSong that});

  (bool, bool, bool, bool) crateApiSongSimpleSongGetShowOptions({
    required SimpleSong that,
  });

  String crateApiSongSimpleSongGetTitle({required SimpleSong that});

  SimpleSong crateApiSongSimpleSongOpen({required String pathStr});

  void crateApiSongSimpleSongSave({required SimpleSong that});

  void crateApiSongSimpleSongSetAutoscrollSpeed({
    required SimpleSong that,
    required BigInt newSpeed,
  });

  void crateApiSongSimpleSongSetCapo({
    required SimpleSong that,
    required int capo,
  });

  void crateApiSongSimpleSongSetShowOptions({
    required SimpleSong that,
    required bool chords,
    required bool rhythm,
    required bool notes,
    required bool fingerings,
  });

  void crateApiSongSimpleSongTranspose({
    required SimpleSong that,
    required int steps,
  });

  void crateApiLibraryAddNewSong({
    required String artist,
    required String title,
    required String text,
    required String pathStr,
  });

  void crateApiLibraryCopyFileOrDir({
    required String inputPathStr,
    required String outputPathStr,
  });

  void crateApiLibraryCopyPathListIn({
    required List<String> pathsStr,
    required String outDirStr,
  });

  void crateApiLibraryCreateDirectory({required String pathStr});

  bool crateApiLibraryExistenceCheck({required String pathStr});

  String crateApiSongGetEditorHelpMsg();

  List<String> crateApiSongGetEditorKeywords();

  List<String> crateApiLibraryGetForbiddenChars();

  void crateApiLibraryImportSong({
    required SimpleSong song,
    required String dirPath,
  });

  Future<void> crateApiLibraryInitApp();

  void crateApiLibraryInitLibrary({required String appDataDir});

  void crateApiLibraryMoveFileOrDir({
    required String inputPathStr,
    required String outputPathStr,
  });

  void crateApiLibraryMovePathListIn({
    required List<String> pathsStr,
    required String outDirStr,
  });

  (List<String>, List<String>, String) crateApiLibraryReadDirectory({
    String? pathStr,
  });

  void crateApiLibraryRemoveFromLibrary({required String pathStr});

  Future<SimpleBlock> crateApiSongSimpleBlockNew({required Block block});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Block;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Block;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BlockPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SimpleSong;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SimpleSong;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SimpleSongPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSongSimpleSongAsText({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongAsTextConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongAsTextConstMeta =>
      const TaskConstMeta(debugName: "SimpleSong_as_text", argNames: ["that"]);

  @override
  void crateApiSongSimpleSongChangeFromEdited({
    required SimpleSong that,
    required String s,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          sse_encode_String(s, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSongSimpleSongChangeFromEditedConstMeta,
        argValues: [that, s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongChangeFromEditedConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_change_from_edited",
        argNames: ["that", "s"],
      );

  @override
  void crateApiSongSimpleSongDetectKey({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongDetectKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongDetectKeyConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_detect_key",
        argNames: ["that"],
      );

  @override
  SimpleSong crateApiSongSimpleSongFromChordpro({required String pathStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSongSimpleSongFromChordproConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongFromChordproConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_from_chordpro",
        argNames: ["pathStr"],
      );

  @override
  List<SimpleSong> crateApiSongSimpleSongFromSongbookpro({
    required String pathStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSongSimpleSongFromSongbookproConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongFromSongbookproConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_from_songbookpro",
        argNames: ["pathStr"],
      );

  @override
  String crateApiSongSimpleSongGetArtist({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetArtistConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetArtistConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_artist",
        argNames: ["that"],
      );

  @override
  BigInt? crateApiSongSimpleSongGetAutoscrollSpeed({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetAutoscrollSpeedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetAutoscrollSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_autoscroll_speed",
        argNames: ["that"],
      );

  @override
  List<SimpleBlock> crateApiSongSimpleSongGetBlocks({
    required SimpleSong that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_simple_block,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetBlocksConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetBlocksConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_blocks",
        argNames: ["that"],
      );

  @override
  int? crateApiSongSimpleSongGetCapo({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_8,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetCapoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetCapoConstMeta =>
      const TaskConstMeta(debugName: "SimpleSong_get_capo", argNames: ["that"]);

  @override
  Map<String, String>? crateApiSongSimpleSongGetFingerings({
    required SimpleSong that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_Map_String_String_None,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetFingeringsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetFingeringsConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_fingerings",
        argNames: ["that"],
      );

  @override
  String crateApiSongSimpleSongGetForEditing({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetForEditingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetForEditingConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_for_editing",
        argNames: ["that"],
      );

  @override
  String? crateApiSongSimpleSongGetKey({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetKeyConstMeta =>
      const TaskConstMeta(debugName: "SimpleSong_get_key", argNames: ["that"]);

  @override
  Future<void> crateApiSongSimpleSongGetMutSong({required SimpleSong that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetMutSongConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetMutSongConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_mut_song",
        argNames: ["that"],
      );

  @override
  String? crateApiSongSimpleSongGetNotes({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetNotesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetNotesConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_notes",
        argNames: ["that"],
      );

  @override
  String? crateApiSongSimpleSongGetPath({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetPathConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetPathConstMeta =>
      const TaskConstMeta(debugName: "SimpleSong_get_path", argNames: ["that"]);

  @override
  (bool, bool, bool, bool) crateApiSongSimpleSongGetShowOptions({
    required SimpleSong that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_bool_bool_bool_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetShowOptionsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetShowOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_show_options",
        argNames: ["that"],
      );

  @override
  String crateApiSongSimpleSongGetTitle({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongGetTitleConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongGetTitleConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_get_title",
        argNames: ["that"],
      );

  @override
  SimpleSong crateApiSongSimpleSongOpen({required String pathStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSongSimpleSongOpenConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongOpenConstMeta =>
      const TaskConstMeta(debugName: "SimpleSong_open", argNames: ["pathStr"]);

  @override
  void crateApiSongSimpleSongSave({required SimpleSong that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSongSimpleSongSaveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongSaveConstMeta =>
      const TaskConstMeta(debugName: "SimpleSong_save", argNames: ["that"]);

  @override
  void crateApiSongSimpleSongSetAutoscrollSpeed({
    required SimpleSong that,
    required BigInt newSpeed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          sse_encode_u_64(newSpeed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongSetAutoscrollSpeedConstMeta,
        argValues: [that, newSpeed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongSetAutoscrollSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_set_autoscroll_speed",
        argNames: ["that", "newSpeed"],
      );

  @override
  void crateApiSongSimpleSongSetCapo({
    required SimpleSong that,
    required int capo,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          sse_encode_u_8(capo, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongSetCapoConstMeta,
        argValues: [that, capo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongSetCapoConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_set_capo",
        argNames: ["that", "capo"],
      );

  @override
  void crateApiSongSimpleSongSetShowOptions({
    required SimpleSong that,
    required bool chords,
    required bool rhythm,
    required bool notes,
    required bool fingerings,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          sse_encode_bool(chords, serializer);
          sse_encode_bool(rhythm, serializer);
          sse_encode_bool(notes, serializer);
          sse_encode_bool(fingerings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongSetShowOptionsConstMeta,
        argValues: [that, chords, rhythm, notes, fingerings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongSetShowOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_set_show_options",
        argNames: ["that", "chords", "rhythm", "notes", "fingerings"],
      );

  @override
  void crateApiSongSimpleSongTranspose({
    required SimpleSong that,
    required int steps,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            that,
            serializer,
          );
          sse_encode_i_32(steps, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleSongTransposeConstMeta,
        argValues: [that, steps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleSongTransposeConstMeta =>
      const TaskConstMeta(
        debugName: "SimpleSong_transpose",
        argNames: ["that", "steps"],
      );

  @override
  void crateApiLibraryAddNewSong({
    required String artist,
    required String title,
    required String text,
    required String pathStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(artist, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(text, serializer);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryAddNewSongConstMeta,
        argValues: [artist, title, text, pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryAddNewSongConstMeta => const TaskConstMeta(
    debugName: "add_new_song",
    argNames: ["artist", "title", "text", "pathStr"],
  );

  @override
  void crateApiLibraryCopyFileOrDir({
    required String inputPathStr,
    required String outputPathStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPathStr, serializer);
          sse_encode_String(outputPathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryCopyFileOrDirConstMeta,
        argValues: [inputPathStr, outputPathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryCopyFileOrDirConstMeta =>
      const TaskConstMeta(
        debugName: "copy_file_or_dir",
        argNames: ["inputPathStr", "outputPathStr"],
      );

  @override
  void crateApiLibraryCopyPathListIn({
    required List<String> pathsStr,
    required String outDirStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(pathsStr, serializer);
          sse_encode_String(outDirStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryCopyPathListInConstMeta,
        argValues: [pathsStr, outDirStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryCopyPathListInConstMeta =>
      const TaskConstMeta(
        debugName: "copy_path_list_in",
        argNames: ["pathsStr", "outDirStr"],
      );

  @override
  void crateApiLibraryCreateDirectory({required String pathStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryCreateDirectoryConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryCreateDirectoryConstMeta =>
      const TaskConstMeta(debugName: "create_directory", argNames: ["pathStr"]);

  @override
  bool crateApiLibraryExistenceCheck({required String pathStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryExistenceCheckConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryExistenceCheckConstMeta =>
      const TaskConstMeta(debugName: "existence_check", argNames: ["pathStr"]);

  @override
  String crateApiSongGetEditorHelpMsg() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongGetEditorHelpMsgConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongGetEditorHelpMsgConstMeta =>
      const TaskConstMeta(debugName: "get_editor_help_msg", argNames: []);

  @override
  List<String> crateApiSongGetEditorKeywords() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongGetEditorKeywordsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongGetEditorKeywordsConstMeta =>
      const TaskConstMeta(debugName: "get_editor_keywords", argNames: []);

  @override
  List<String> crateApiLibraryGetForbiddenChars() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_Char,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryGetForbiddenCharsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetForbiddenCharsConstMeta =>
      const TaskConstMeta(debugName: "get_forbidden_chars", argNames: []);

  @override
  void crateApiLibraryImportSong({
    required SimpleSong song,
    required String dirPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
            song,
            serializer,
          );
          sse_encode_String(dirPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryImportSongConstMeta,
        argValues: [song, dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryImportSongConstMeta => const TaskConstMeta(
    debugName: "import_song",
    argNames: ["song", "dirPath"],
  );

  @override
  Future<void> crateApiLibraryInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiLibraryInitLibrary({required String appDataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appDataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryInitLibraryConstMeta,
        argValues: [appDataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryInitLibraryConstMeta =>
      const TaskConstMeta(debugName: "init_library", argNames: ["appDataDir"]);

  @override
  void crateApiLibraryMoveFileOrDir({
    required String inputPathStr,
    required String outputPathStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPathStr, serializer);
          sse_encode_String(outputPathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryMoveFileOrDirConstMeta,
        argValues: [inputPathStr, outputPathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryMoveFileOrDirConstMeta =>
      const TaskConstMeta(
        debugName: "move_file_or_dir",
        argNames: ["inputPathStr", "outputPathStr"],
      );

  @override
  void crateApiLibraryMovePathListIn({
    required List<String> pathsStr,
    required String outDirStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(pathsStr, serializer);
          sse_encode_String(outDirStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryMovePathListInConstMeta,
        argValues: [pathsStr, outDirStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryMovePathListInConstMeta =>
      const TaskConstMeta(
        debugName: "move_path_list_in",
        argNames: ["pathsStr", "outDirStr"],
      );

  @override
  (List<String>, List<String>, String) crateApiLibraryReadDirectory({
    String? pathStr,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_list_string_list_string_string,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryReadDirectoryConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryReadDirectoryConstMeta =>
      const TaskConstMeta(debugName: "read_directory", argNames: ["pathStr"]);

  @override
  void crateApiLibraryRemoveFromLibrary({required String pathStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pathStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryRemoveFromLibraryConstMeta,
        argValues: [pathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryRemoveFromLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "remove_from_library",
        argNames: ["pathStr"],
      );

  @override
  Future<SimpleBlock> crateApiSongSimpleBlockNew({required Block block}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
            block,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_simple_block,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSongSimpleBlockNewConstMeta,
        argValues: [block],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSongSimpleBlockNewConstMeta =>
      const TaskConstMeta(debugName: "simple_block_new", argNames: ["block"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Block => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Block => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SimpleSong => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SimpleSong => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SimpleSong
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SimpleSongImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SimpleSong
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SimpleSongImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Block
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlockImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SimpleSong
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SimpleSongImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_Char(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return String.fromCharCode(raw);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  Block
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlockImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SimpleSong
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SimpleSongImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<SimpleSong>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong,
        )
        .toList();
  }

  @protected
  List<String> dco_decode_list_Char(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_Char).toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<SimpleBlock> dco_decode_list_simple_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_simple_block).toList();
  }

  @protected
  List<SimpleLine> dco_decode_list_simple_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_simple_line).toList();
  }

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_Map_String_String_None(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  (bool, bool, bool, bool) dco_decode_record_bool_bool_bool_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) {
      throw Exception('Expected 4 elements, got ${arr.length}');
    }
    return (
      dco_decode_bool(arr[0]),
      dco_decode_bool(arr[1]),
      dco_decode_bool(arr[2]),
      dco_decode_bool(arr[3]),
    );
  }

  @protected
  (List<String>, List<String>, String)
  dco_decode_record_list_string_list_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_String(arr[0]),
      dco_decode_list_String(arr[1]),
      dco_decode_String(arr[2]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SimpleBlock dco_decode_simple_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SimpleBlock(
      title: dco_decode_opt_String(arr[0]),
      lines: dco_decode_list_simple_line(arr[1]),
      notes: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SimpleLine dco_decode_simple_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SimpleLine_Row(
          dco_decode_String(raw[1]),
          dco_decode_String(raw[2]),
          dco_decode_String(raw[3]),
        );
      case 1:
        return SimpleLine_ChordsLine(dco_decode_String(raw[1]));
      case 2:
        return SimpleLine_PlainText(dco_decode_String(raw[1]));
      case 3:
        return SimpleLine_Tab(dco_decode_String(raw[1]));
      case 4:
        return SimpleLine_EmptyLine();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SimpleSong
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SimpleSongImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SimpleSong
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SimpleSongImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Block
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BlockImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SimpleSong
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SimpleSongImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_Char(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return inner;
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  Block
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BlockImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SimpleSong
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SimpleSongImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<SimpleSong>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimpleSong>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_Char(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_Char(deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<SimpleBlock> sse_decode_list_simple_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimpleBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_simple_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<SimpleLine> sse_decode_list_simple_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimpleLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_simple_line(deserializer));
    }
    return ans_;
  }

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_Map_String_String_None(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (bool, bool, bool, bool) sse_decode_record_bool_bool_bool_bool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_bool(deserializer);
    var var_field1 = sse_decode_bool(deserializer);
    var var_field2 = sse_decode_bool(deserializer);
    var var_field3 = sse_decode_bool(deserializer);
    return (var_field0, var_field1, var_field2, var_field3);
  }

  @protected
  (List<String>, List<String>, String)
  sse_decode_record_list_string_list_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_String(deserializer);
    var var_field1 = sse_decode_list_String(deserializer);
    var var_field2 = sse_decode_String(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SimpleBlock sse_decode_simple_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_lines = sse_decode_list_simple_line(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return SimpleBlock(title: var_title, lines: var_lines, notes: var_notes);
  }

  @protected
  SimpleLine sse_decode_simple_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        var var_field1 = sse_decode_String(deserializer);
        var var_field2 = sse_decode_String(deserializer);
        return SimpleLine_Row(var_field0, var_field1, var_field2);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return SimpleLine_ChordsLine(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return SimpleLine_PlainText(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return SimpleLine_Tab(var_field0);
      case 4:
        return SimpleLine_EmptyLine();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SimpleSong self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SimpleSongImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SimpleSong self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SimpleSongImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
    Block self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BlockImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SimpleSong self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SimpleSongImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Char(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBlock(
    Block self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BlockImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    SimpleSong self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SimpleSongImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
    List<SimpleSong> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSimpleSong(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_Char(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Char(item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_simple_block(
    List<SimpleBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_simple_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_simple_line(
    List<SimpleLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_simple_line(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_Map_String_String_None(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_record_bool_bool_bool_bool(
    (bool, bool, bool, bool) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.$1, serializer);
    sse_encode_bool(self.$2, serializer);
    sse_encode_bool(self.$3, serializer);
    sse_encode_bool(self.$4, serializer);
  }

  @protected
  void sse_encode_record_list_string_list_string_string(
    (List<String>, List<String>, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.$1, serializer);
    sse_encode_list_String(self.$2, serializer);
    sse_encode_String(self.$3, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_simple_block(SimpleBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_list_simple_line(self.lines, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_simple_line(SimpleLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SimpleLine_Row(
        field0: final field0,
        field1: final field1,
        field2: final field2,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
        sse_encode_String(field1, serializer);
        sse_encode_String(field2, serializer);
      case SimpleLine_ChordsLine(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case SimpleLine_PlainText(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case SimpleLine_Tab(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case SimpleLine_EmptyLine():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class BlockImpl extends RustOpaque implements Block {
  // Not to be used by end users
  BlockImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BlockImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Block,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Block,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BlockPtr,
  );
}

@sealed
class SimpleSongImpl extends RustOpaque implements SimpleSong {
  // Not to be used by end users
  SimpleSongImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SimpleSongImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SimpleSong,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SimpleSong,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SimpleSongPtr,
  );

  String asText() =>
      RustLib.instance.api.crateApiSongSimpleSongAsText(that: this);

  void changeFromEdited({required String s}) => RustLib.instance.api
      .crateApiSongSimpleSongChangeFromEdited(that: this, s: s);

  void detectKey() =>
      RustLib.instance.api.crateApiSongSimpleSongDetectKey(that: this);

  String getArtist() =>
      RustLib.instance.api.crateApiSongSimpleSongGetArtist(that: this);

  BigInt? getAutoscrollSpeed() =>
      RustLib.instance.api.crateApiSongSimpleSongGetAutoscrollSpeed(that: this);

  List<SimpleBlock> getBlocks() =>
      RustLib.instance.api.crateApiSongSimpleSongGetBlocks(that: this);

  int? getCapo() =>
      RustLib.instance.api.crateApiSongSimpleSongGetCapo(that: this);

  Map<String, String>? getFingerings() =>
      RustLib.instance.api.crateApiSongSimpleSongGetFingerings(that: this);

  String getForEditing() =>
      RustLib.instance.api.crateApiSongSimpleSongGetForEditing(that: this);

  String? getKey() =>
      RustLib.instance.api.crateApiSongSimpleSongGetKey(that: this);

  Future<void> getMutSong() =>
      RustLib.instance.api.crateApiSongSimpleSongGetMutSong(that: this);

  String? getNotes() =>
      RustLib.instance.api.crateApiSongSimpleSongGetNotes(that: this);

  String? getPath() =>
      RustLib.instance.api.crateApiSongSimpleSongGetPath(that: this);

  (bool, bool, bool, bool) getShowOptions() =>
      RustLib.instance.api.crateApiSongSimpleSongGetShowOptions(that: this);

  String getTitle() =>
      RustLib.instance.api.crateApiSongSimpleSongGetTitle(that: this);

  void save() => RustLib.instance.api.crateApiSongSimpleSongSave(that: this);

  void setAutoscrollSpeed({required BigInt newSpeed}) => RustLib.instance.api
      .crateApiSongSimpleSongSetAutoscrollSpeed(that: this, newSpeed: newSpeed);

  void setCapo({required int capo}) => RustLib.instance.api
      .crateApiSongSimpleSongSetCapo(that: this, capo: capo);

  void setShowOptions({
    required bool chords,
    required bool rhythm,
    required bool notes,
    required bool fingerings,
  }) => RustLib.instance.api.crateApiSongSimpleSongSetShowOptions(
    that: this,
    chords: chords,
    rhythm: rhythm,
    notes: notes,
    fingerings: fingerings,
  );

  void transpose({required int steps}) => RustLib.instance.api
      .crateApiSongSimpleSongTranspose(that: this, steps: steps);
}
