// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'song.dart';

// These functions are ignored because they are not marked as `pub`: `copy_all`, `copy_recursive`, `move_all`, `remove_all`

Future<void> exportBackup({
  required String outputPathStr,
  required Map<String, String> settings,
  String? fontsPath,
  String? backgroundPath,
}) => RustLib.instance.api.crateApiLibraryExportBackup(
  outputPathStr: outputPathStr,
  settings: settings,
  fontsPath: fontsPath,
  backgroundPath: backgroundPath,
);

Future<Map<String, String>> importBackup({
  required String backupPathStr,
  required String fontsPathStr,
  required String backgroundPathStr,
}) => RustLib.instance.api.crateApiLibraryImportBackup(
  backupPathStr: backupPathStr,
  fontsPathStr: fontsPathStr,
  backgroundPathStr: backgroundPathStr,
);

(List<String>, List<String>, String) readDirectory({String? pathStr}) =>
    RustLib.instance.api.crateApiLibraryReadDirectory(pathStr: pathStr);

List<String> search({required String pathStr, required String query}) =>
    RustLib.instance.api.crateApiLibrarySearch(pathStr: pathStr, query: query);

Future<List<String>> tagSearch({required List<String> tags}) =>
    RustLib.instance.api.crateApiLibraryTagSearch(tags: tags);

Future<Map<String, Set<String>>> getTagMap() =>
    RustLib.instance.api.crateApiLibraryGetTagMap();

void createDirectory({required String pathStr}) =>
    RustLib.instance.api.crateApiLibraryCreateDirectory(pathStr: pathStr);

void removeFromLibrary({required String pathStr}) =>
    RustLib.instance.api.crateApiLibraryRemoveFromLibrary(pathStr: pathStr);

void moveFileOrDir({
  required String inputPathStr,
  required String outputPathStr,
}) => RustLib.instance.api.crateApiLibraryMoveFileOrDir(
  inputPathStr: inputPathStr,
  outputPathStr: outputPathStr,
);

void copyFileOrDir({
  required String inputPathStr,
  required String outputPathStr,
}) => RustLib.instance.api.crateApiLibraryCopyFileOrDir(
  inputPathStr: inputPathStr,
  outputPathStr: outputPathStr,
);

void copyPathListIn({
  required List<String> pathsStr,
  required String outDirStr,
}) => RustLib.instance.api.crateApiLibraryCopyPathListIn(
  pathsStr: pathsStr,
  outDirStr: outDirStr,
);

void movePathListIn({
  required List<String> pathsStr,
  required String outDirStr,
}) => RustLib.instance.api.crateApiLibraryMovePathListIn(
  pathsStr: pathsStr,
  outDirStr: outDirStr,
);

void addNewSong({
  required String artist,
  required String title,
  required String text,
  required String pathStr,
  Set<String>? tags,
}) => RustLib.instance.api.crateApiLibraryAddNewSong(
  artist: artist,
  title: title,
  text: text,
  pathStr: pathStr,
  tags: tags,
);

void importSong({required SimpleSong song, String? dirPath}) => RustLib
    .instance
    .api
    .crateApiLibraryImportSong(song: song, dirPath: dirPath);

void resetLibrary() => RustLib.instance.api.crateApiLibraryResetLibrary();

bool existenceCheck({required String pathStr}) =>
    RustLib.instance.api.crateApiLibraryExistenceCheck(pathStr: pathStr);

List<String> getForbiddenChars() =>
    RustLib.instance.api.crateApiLibraryGetForbiddenChars();

List<String> getAvailableSites() =>
    RustLib.instance.api.crateApiLibraryGetAvailableSites();

String getLibraryPath() => RustLib.instance.api.crateApiLibraryGetLibraryPath();

String? getDefaultLibraryPath() =>
    RustLib.instance.api.crateApiLibraryGetDefaultLibraryPath();

void setDataDirEnv({required String dataDir}) =>
    RustLib.instance.api.crateApiLibrarySetDataDirEnv(dataDir: dataDir);

String? getDataDirEnv() => RustLib.instance.api.crateApiLibraryGetDataDirEnv();

Future<void> moveLibrary({required String newDir}) =>
    RustLib.instance.api.crateApiLibraryMoveLibrary(newDir: newDir);
