// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(List<String>, List<String>) readDirectory({String? pathStr}) =>
    RustLib.instance.api.crateApiLibraryReadDirectory(pathStr: pathStr);

void initLibrary({required String appDataDir}) =>
    RustLib.instance.api.crateApiLibraryInitLibrary(appDataDir: appDataDir);
