// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(List<String>, List<String>, String) readDirectory({String? pathStr}) =>
    RustLib.instance.api.crateApiLibraryReadDirectory(pathStr: pathStr);

void createDirectory({required String pathStr}) =>
    RustLib.instance.api.crateApiLibraryCreateDirectory(pathStr: pathStr);

void removeFromLibrary({required String pathStr}) =>
    RustLib.instance.api.crateApiLibraryRemoveFromLibrary(pathStr: pathStr);

void moveFileOrDir({
  required String inputPathStr,
  required String outputPathStr,
}) => RustLib.instance.api.crateApiLibraryMoveFileOrDir(
  inputPathStr: inputPathStr,
  outputPathStr: outputPathStr,
);

void addNewSong({
  required String artist,
  required String title,
  required String text,
  required String pathStr,
}) => RustLib.instance.api.crateApiLibraryAddNewSong(
  artist: artist,
  title: title,
  text: text,
  pathStr: pathStr,
);

bool existenceCheck({required String pathStr}) =>
    RustLib.instance.api.crateApiLibraryExistenceCheck(pathStr: pathStr);

List<String> getForbiddenChars() =>
    RustLib.instance.api.crateApiLibraryGetForbiddenChars();

void initLibrary({required String appDataDir}) =>
    RustLib.instance.api.crateApiLibraryInitLibrary(appDataDir: appDataDir);
