// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'song.freezed.dart';

String getEditorHelpMsg() =>
    RustLib.instance.api.crateApiSongGetEditorHelpMsg();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Block>>
abstract class Block implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SimpleSong>>
abstract class SimpleSong implements RustOpaqueInterface {
  String asText();

  void changeFromEdited({required String s});

  void detectKey();

  static SimpleSong fromChordpro({required String pathStr}) =>
      RustLib.instance.api.crateApiSongSimpleSongFromChordpro(pathStr: pathStr);

  static List<SimpleSong> fromSongbookpro({required String pathStr}) => RustLib
      .instance
      .api
      .crateApiSongSimpleSongFromSongbookpro(pathStr: pathStr);

  String getArtist();

  BigInt? getAutoscrollSpeed();

  List<SimpleBlock> getBlocks();

  int? getCapo();

  String getForEditing();

  String? getKey();

  Future<void> getMutSong();

  String? getNotes();

  (bool, bool, bool, bool) getShowOptions();

  String getTitle();

  static SimpleSong open({required String pathStr}) =>
      RustLib.instance.api.crateApiSongSimpleSongOpen(pathStr: pathStr);

  void save();

  void setAutoscrollSpeed({required BigInt newSpeed});

  void setCapo({required int capo});

  void setShowOptions({
    required bool chords,
    required bool rhythm,
    required bool notes,
    required bool fingerings,
  });

  void transpose({required int steps});
}

class SimpleBlock {
  final String? title;
  final List<SimpleLine> lines;
  final String? notes;

  const SimpleBlock({this.title, required this.lines, this.notes});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SimpleBlock> newInstance({required Block block}) =>
      RustLib.instance.api.crateApiSongSimpleBlockNew(block: block);

  @override
  int get hashCode => title.hashCode ^ lines.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleBlock &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          lines == other.lines &&
          notes == other.notes;
}

@freezed
sealed class SimpleLine with _$SimpleLine {
  const SimpleLine._();

  const factory SimpleLine.row(String field0, String field1, String field2) =
      SimpleLine_Row;
  const factory SimpleLine.chordsLine(String field0) = SimpleLine_ChordsLine;
  const factory SimpleLine.plainText(String field0) = SimpleLine_PlainText;
  const factory SimpleLine.tab(String field0) = SimpleLine_Tab;
  const factory SimpleLine.emptyLine() = SimpleLine_EmptyLine;
}
