// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'song.freezed.dart';

String getEditorHelpMsg() =>
    RustLib.instance.api.crateApiSongGetEditorHelpMsg();

List<String> getEditorKeywords() =>
    RustLib.instance.api.crateApiSongGetEditorKeywords();

String chordsSymbol() => RustLib.instance.api.crateApiSongChordsSymbol();

String rhythmSymbol() => RustLib.instance.api.crateApiSongRhythmSymbol();

String textSymbol() => RustLib.instance.api.crateApiSongTextSymbol();

String rowStart() => RustLib.instance.api.crateApiSongRowStart();

String rowEnd() => RustLib.instance.api.crateApiSongRowEnd();

String titleSymbol() => RustLib.instance.api.crateApiSongTitleSymbol();

String blockNoteSymbol() => RustLib.instance.api.crateApiSongBlockNoteSymbol();

String chordsLineSymbol() =>
    RustLib.instance.api.crateApiSongChordsLineSymbol();

String noteLineSymbol() => RustLib.instance.api.crateApiSongNoteLineSymbol();

String emptyLineSymbol() => RustLib.instance.api.crateApiSongEmptyLineSymbol();

String blockStart() => RustLib.instance.api.crateApiSongBlockStart();

String blockEnd() => RustLib.instance.api.crateApiSongBlockEnd();

String plainTextStart() => RustLib.instance.api.crateApiSongPlainTextStart();

String plainTextEnd() => RustLib.instance.api.crateApiSongPlainTextEnd();

String tabStartSymbol() => RustLib.instance.api.crateApiSongTabStartSymbol();

String tabEndSymbol() => RustLib.instance.api.crateApiSongTabEndSymbol();

String songNoteStartSymbol() =>
    RustLib.instance.api.crateApiSongSongNoteStartSymbol();

String songNoteEndSymbol() =>
    RustLib.instance.api.crateApiSongSongNoteEndSymbol();

String metadataStart() => RustLib.instance.api.crateApiSongMetadataStart();

String metadataEnd() => RustLib.instance.api.crateApiSongMetadataEnd();

String songTitleSymbol() => RustLib.instance.api.crateApiSongSongTitleSymbol();

String songArtistSymbol() =>
    RustLib.instance.api.crateApiSongSongArtistSymbol();

String songKeySymbol() => RustLib.instance.api.crateApiSongSongKeySymbol();

String songCapoSymbol() => RustLib.instance.api.crateApiSongSongCapoSymbol();

String songAutoscrollSpeedSymbol() =>
    RustLib.instance.api.crateApiSongSongAutoscrollSpeedSymbol();

String songShowOptionsSymbol() =>
    RustLib.instance.api.crateApiSongSongShowOptionsSymbol();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Block>>
abstract class Block implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SimpleSong>>
abstract class SimpleSong implements RustOpaqueInterface {
  String asText();

  void changeFromEdited({required String s});

  void detectKey();

  static SimpleSong fromChordpro({required String pathStr}) =>
      RustLib.instance.api.crateApiSongSimpleSongFromChordpro(pathStr: pathStr);

  static List<SimpleSong> fromSongbookpro({required String pathStr}) => RustLib
      .instance
      .api
      .crateApiSongSimpleSongFromSongbookpro(pathStr: pathStr);

  String getArtist();

  BigInt? getAutoscrollSpeed();

  List<SimpleBlock> getBlocks();

  int? getCapo();

  Map<String, String>? getFingerings();

  String getForEditing();

  String? getKey();

  Future<void> getMutSong();

  String? getNotes();

  String? getPath();

  (bool, bool, bool, bool) getShowOptions();

  String getTitle();

  static SimpleSong open({required String pathStr}) =>
      RustLib.instance.api.crateApiSongSimpleSongOpen(pathStr: pathStr);

  void save();

  void setAutoscrollSpeed({required BigInt newSpeed});

  void setCapo({required int capo});

  void setShowOptions({
    required bool chords,
    required bool rhythm,
    required bool notes,
    required bool fingerings,
  });

  void transpose({required int steps});
}

class SimpleBlock {
  final String? title;
  final List<SimpleLine> lines;
  final String? notes;

  const SimpleBlock({this.title, required this.lines, this.notes});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SimpleBlock> newInstance({required Block block}) =>
      RustLib.instance.api.crateApiSongSimpleBlockNew(block: block);

  @override
  int get hashCode => title.hashCode ^ lines.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleBlock &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          lines == other.lines &&
          notes == other.notes;
}

@freezed
sealed class SimpleLine with _$SimpleLine {
  const SimpleLine._();

  const factory SimpleLine.row(String field0, String field1, String field2) =
      SimpleLine_Row;
  const factory SimpleLine.chordsLine(String field0) = SimpleLine_ChordsLine;
  const factory SimpleLine.noteLine(String field0) = SimpleLine_NoteLine;
  const factory SimpleLine.plainText(String field0) = SimpleLine_PlainText;
  const factory SimpleLine.tab(String field0) = SimpleLine_Tab;
  const factory SimpleLine.emptyLine() = SimpleLine_EmptyLine;
}
