// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<SimpleFingering> getFingeringsForChord({required String chord}) =>
    RustLib.instance.api.crateApiTheoryGetFingeringsForChord(chord: chord);

void setFingeringGlobal({required SimpleFingering fingering}) =>
    RustLib.instance.api.crateApiTheorySetFingeringGlobal(fingering: fingering);

SimpleNoteArray25Array6 getFretboard({required SimpleNoteArray6 tuning}) =>
    RustLib.instance.api.crateApiTheoryGetFretboard(tuning: tuning);

void setSharpOnly({required bool isSharpOnly}) =>
    RustLib.instance.api.crateApiTheorySetSharpOnly(isSharpOnly: isSharpOnly);

bool? getSharpOnly() => RustLib.instance.api.crateApiTheoryGetSharpOnly();

SimpleNoteArray6 getStandartTuning() =>
    RustLib.instance.api.crateApiTheoryGetStandartTuning();

List<SimpleKey> getAllKeys() => RustLib.instance.api.crateApiTheoryGetAllKeys();

class SimpleNoteArray25 extends NonGrowableListView<SimpleNote> {
  static const arraySize = 25;

  @internal
  List<SimpleNote> get inner => _inner;
  final List<SimpleNote> _inner;

  SimpleNoteArray25(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  SimpleNoteArray25.init(SimpleNote fill)
    : this(List<SimpleNote>.filled(arraySize, fill));
}

class SimpleNoteArray25Array6 extends NonGrowableListView<SimpleNoteArray25> {
  static const arraySize = 6;

  @internal
  List<SimpleNoteArray25> get inner => _inner;
  final List<SimpleNoteArray25> _inner;

  SimpleNoteArray25Array6(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  SimpleNoteArray25Array6.init(SimpleNoteArray25 fill)
    : this(List<SimpleNoteArray25>.filled(arraySize, fill));
}

class SimpleNoteArray6 extends NonGrowableListView<SimpleNote> {
  static const arraySize = 6;

  @internal
  List<SimpleNote> get inner => _inner;
  final List<SimpleNote> _inner;

  SimpleNoteArray6(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  SimpleNoteArray6.init(SimpleNote fill)
    : this(List<SimpleNote>.filled(arraySize, fill));
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Fingering>>
abstract class Fingering implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Key>>
abstract class Key implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SimpleFingering>>
abstract class SimpleFingering implements RustOpaqueInterface {
  Fingering get fingering;

  set fingering(Fingering fingering);

  static SimpleFingering? fromString({
    required String fingering,
    required String chord,
  }) => RustLib.instance.api.crateApiTheorySimpleFingeringFromString(
    fingering: fingering,
    chord: chord,
  );

  @override
  String toString();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SimpleKey>>
abstract class SimpleKey implements RustOpaqueInterface {
  Key get key;

  set key(Key key);

  static SimpleKey? fromString({required String s}) =>
      RustLib.instance.api.crateApiTheorySimpleKeyFromString(s: s);

  bool isMinor();

  @override
  String toString();

  void transpose({required int steps});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SimpleNote>>
abstract class SimpleNote implements RustOpaqueInterface {
  @override
  String toString();
}
